### ISSUE TITLE
NTP Server Screen?

### ISSUE THREAD

**Issue by elvisimprsntr** [georou/pfsense-LCDproc-NUT-UPS-Monitor#1]
I have a new, old stock Crystalfontz XES635BK on the way.  Thanks for the tweaks to show NUT status.   I also see you just submitted a redmine ticket. https://redmine.pfsense.org/issues/14321

I run a Stratum 0 GPS PPS Server.  How difficult would it be to add a NTP server config menu and stats screen? Or does the built in Time screen already do that?

<img width="596" alt="Screenshot 2023-04-29 at 6 13 26 AM" src="https://user-images.githubusercontent.com/1215508/235298945-c3545810-6d9c-44b4-8b0b-b97d360f34a5.png">

![34C6EA6D-EF71-4817-8BDC-06FD126626D1](https://user-images.githubusercontent.com/1215508/235299193-46fad5b1-31ca-4163-a868-54d7688ac029.png)

**Comment by georou** [comment]
Hi mate, you're welcome for the NUT info screen :) Please let me know if you run into any bugs or weirdness with it.

To display the NTP server info like the dashboard, should be straight forward. Following the breadcrumbs from that page starts here: https://github.com/pfsense/pfsense/blob/master/src/usr/local/www/widgets/widgets/ntp_status.widget.php#L232

From that dashboard widget, which info is the most important to show on the LCD in your opinion?

There's also the NTP status page too, which from there would be useful?
![Screenshot 2023-04-29 222637](https://user-images.githubusercontent.com/19909711/235302710-d5d09589-01c1-4a87-af30-94d419515440.jpg)

**Comment by georou** [comment]
Hi, I've added the NTP screen: https://github.com/georou/FreeBSD-ports/blob/lcdproc-ntp/sysutils/pfSense-pkg-LCDproc/files/usr/local/pkg/lcdproc_client.php#L110

Same instructions as the readme here, copy both screen and client over. Obviously make a local backup before overwriting and the usual jazz.

Tell me what you think of it :)

**Comment by elvisimprsntr** [comment]
Thanks.  I started tinkering with it, but you beat me to it.  My Crystalfontz XES635BK is due to arrive on Monday USA

**Comment by elvisimprsntr** [comment]
While waiting on my 4x20 display to arrive, I downloaded and copied the files to the respective directories, restarted the LCDproc daemon, but received the following errors

`Crash report begins.  Anonymous machine information:
amd64
12.3-STABLE
FreeBSD 12.3-STABLE RELENG_2_6_0-n226742-1285d6d205f pfSense
Crash report details:
PHP Errors:
[30-Apr-2023 16:00:43 America/New_York] PHP Fatal error:  Uncaught Error: Call to undefined function config_get_path() in /usr/local/pkg/lcdproc_client.php:111
Stack trace:
#0 /usr/local/pkg/lcdproc_client.php(1355): lcdproc_get_ntp_status()
#1 /usr/local/pkg/lcdproc_client.php(1517): lcdproc_loop_status(Resource id #50)
#2 {main}
  thrown in /usr/local/pkg/lcdproc_client.php on line 111
No FreeBSD crash data found.`

**Comment by georou** [comment]
Thank you for trying. 

Check out the new commit, that should fix it now.

**Comment by elvisimprsntr** [comment]
Thanks. No errors.  Now the wait for the LCD display

**Comment by georou** [comment]
Awesome.

Curiously, did you purchase it directly from CrystalFontz? They aren't as plentiful in Australia, sadly.

You've sparked my interest with running a stratum 0 locally. Might have to dig out a GPS module I put on the backburner a few years ago I intended to use with a Raspberry Pi.

**Comment by elvisimprsntr** [comment]
I am too cheap to pay full price, so I purchased new old stock off evilBay for $25 USD. https://www.ebay.com/itm/363731262299

Here is my GPS PPS NTP Server Implementation. 
[Stratum 1 GPS NTP Server.pdf](https://github.com/georou/pfsense-LCDproc-NUT-UPS-Monitor/files/11362562/Stratum.1.GPS.NTP.Server.pdf)

**Comment by elvisimprsntr** [comment]
My XES635BK arrived today.   Plug and play.  Navigation buttons work.  Not bad for $25 USD. New they are $200 USD.  
Might need just a little cleanup.  Stray "y" on the screen (not sure if that is my unit or not).  I might want to see the NTP delay, offset, jitter rather than the CPU summary lines.  Now I have something to tinker with.  


![7D1D8A30-FC76-44D9-88B2-2A9CD1BEE203_1_105_c](https://user-images.githubusercontent.com/1215508/235540311-f5d867ea-df3a-484e-b753-35965ee1bf10.jpeg)
![BB1192CE-A691-4957-AEB9-CADB8350DCD0_1_105_c](https://user-images.githubusercontent.com/1215508/235540314-97bddff1-5349-4702-9622-66e6725f2b79.jpeg)

**Comment by georou** [comment]
That is a very good price for it. They seem like solid units. Looks great, too!

Cheers for the pdf. I've now got my GPS providing time on my test box. That should help out tinkering, too.

Question, the buttons on the unit. Can you cycle through the screens you enabled? Or is it only as the "pfSense control menu" setting says, just halt and reboot?

That stray 'y' is interesting. Showing on the NTP screen is even more interesting since the bottom 2 rows is the code from the lcdproc package. I would think it might be something in my additions but also showing there seems, not. If you select some other screens, does it show in all of them too? Try 16x4 mode too.

**Comment by elvisimprsntr** [comment]
A1: The buttons don't allow one to scroll through the screens.  Only enable/select the display specific options (blacklight, brightness, contrast, etc.) and the pfSense control menu.  
A2: It's a 20x4 display..  The stray "y" seems to be from the boot splash screen.  There is also a stray "6" on the forth row from displaying the  v1.6 firmware on the splash screen, which clears when I pull up some of the display settings, which overwrites the 20th column on the 4th row.  
A3: I haven't tested any of the other stock LCDproc pfSense screens yet.  

🍻

**Comment by georou** [comment]
Cheers ^

I've pushed another update that uses the all the rows and shows extra metrics. Not quite happy with the gps satellites function though, feels a bit messy. But for the most part, the rest works.

I noticed that there's LED status in the code too - albeit CF633. 1: Interface status(up/down), 2: CARP status(up/down), 3: CPU usage(<50% usage), 4: Gateway status(up/down). Does that line up with your unit? At least green for CPU from your picture looks accurate? Neat little box.

Edit: I see changing the driver in lcdproc shows a new checkbox for the LEDs. Interesting yours shows orange for interfaces.

**Comment by elvisimprsntr** [comment]
Thanks for the the updates.  Yes, the lights align with the status.  The first LED is yellowish.   Perhaps that is why it was $25 USD on evilBay. I couldn't care less at that price. 

According to the manual:

`The front of the display has four bicolor (red + green), LED status lights. The LEDs' brightness can be set
by the host software that allows for smoothly adjusting the LEDs to produce other colors (for example,
yellow, and orange).`

I moved my display from my dedicated NTP server to my primary pfSense firewall, so it does not have satellite data.  I'll connect it directly to my NTP server next.  

`Crash report begins.  Anonymous machine information: 
amd64 
12.3-STABLE
FreeBSD 12.3-STABLE RELENG_2_6_0-n226742-1285d6d205f pfSense 
Crash report details: 
PHP Errors: 
[03-May-2023 05:25:21 America/New_York] PHP Fatal error:  Uncaught Error: Call to undefined function config_get_path() in /usr/local/pkg/lcdproc_client.php:129 
Stack trace: 
#0 /usr/local/pkg/lcdproc_client.php(1366): lcdproc_get_ntp_gps_sat_count() 
#1 /usr/local/pkg/lcdproc_client.php(1559): lcdproc_loop_status(Resource id #50) 
#2 {main} 
thrown in /usr/local/pkg/lcdproc_client.php on line 129 
No FreeBSD crash data found.`

**Comment by elvisimprsntr** [comment]
I hooked up my display to my dedicated NTP server and got a similar error message

`Crash report begins.  Anonymous machine information:
amd64
12.3-STABLE
FreeBSD 12.3-STABLE RELENG_2_6_0-n226742-1285d6d205f pfSense
*Crash report details:
PHP Errors:
[03-May-2023 10:08:33 America/New_York] PHP Fatal error:  Uncaught Error: Call to undefined function config_get_path() in /usr/local/pkg/lcdproc_client.php:129
Stack trace:
#0 /usr/local/pkg/lcdproc_client.php(1366): lcdproc_get_ntp_gps_sat_count()
#1 /usr/local/pkg/lcdproc_client.php(1559): lcdproc_loop_status(Resource id #50)
#2 {main}
  thrown in /usr/local/pkg/lcdproc_client.php on line 129
No FreeBSD crash data found.`


I wonder if it is because on don't send the NMEA message that include satellites in view, only in use.  (GPGGA)

<img width="1143" alt="Screenshot 2023-05-03 at 10 32 20 AM" src="https://user-images.githubusercontent.com/1215508/235947964-30275697-a141-4812-9b78-a888a5bd2be8.png">

**Comment by georou** [comment]
Yeah, interesting for the LEDs. Might need some further looking at what colour the code sets. It does some exponential expressions: https://github.com/georou/FreeBSD-ports/blob/lcdproc-ntp/sysutils/pfSense-pkg-LCDproc/files/usr/local/pkg/lcdproc_client.php#L1210 

Ah, I forgot you're on 2.6.0 pfsense. I'm working on a 2.7.0 dev build. I need to dig in why the function doesn't work between builds. See the latest push, should work now. I laid my head down to sleep last night and it hit me out of nowhere - "you forgot to change the function because it won't work on Elvis' 2.6.0 build" - doh!

**Comment by elvisimprsntr** [comment]
I upgraded my dedicated NTP server to 2.7.0-DEVEL build.  

I spent a good part of my Sunday trying to figure out how to send the command to the CFA635 to clear the factory splash screen.  There does not appear to be anything in the LCDproc config files or the pfSense PHP to clear the screen.   I was able to figure out what CRC algorithm CF displays are using (CRC-16/X-25) and tried to send the raw hex to the display.  
https://crccalc.com/?crc=0600&method=CRC-16/X-25&datatype=hex&outtype=0

CF documentation is a little vague and they only include some sample code containing the look up table.  
https://github.com/crystalfontz/cfa_linux_examples/blob/master/include/cf_packet.c

I ended up connecting the CFA635 to a Proxmox Windows VM and used the CrystalFontz CFTEST utility to send the command to clear the splash screen and save the power up state, effectively erasing the factory splash screen.  No more stray characters!  

I pulled your latest commits as of this morning and have them running.  No errors.  Looks good!
Now if we can only get them to bake it into 2.7.0 official release.  

![IMG_1820](https://user-images.githubusercontent.com/1215508/236707187-c86620aa-3c58-4d2e-b937-11b887699ee8.jpeg)


![IMG_1815](https://user-images.githubusercontent.com/1215508/236706459-a2b2ea1b-f01a-40f0-ada6-eed878899837.jpeg)

🍻

**Comment by georou** [comment]
Oh wow, nice little adventure. Good to hear you got it cleared and it was the issue. I'll have to remember using your idea with the util to clear the screen in the future.

The LED indicators are still interesting to me. I'm thinking of a way to have the option of replacing the CARP indicator with something more useful if it isn't used. Something for the future.

**Comment by elvisimprsntr** [comment]
Maybe some of the LEDs can be replaced with a GPS lock or UPS status signal?   The question would be how to avoid conflicts with the default LED indicators?  Perhaps a prerequisite to have the default LED status disabled and add LED control as a sub option under the NUT and NTP screens. Or completely rewrite the main LED control setting to make each LED configurable via a drop down menu.  The latter seems like a lot more effort, but it may be the only way given the existing pfSense PHP

BTW, I bought a second XES635BK which is due to arrive this week.  I can send you one if you like. Just drop me a note at my g m a i l

**Comment by georou** [comment]
I really like the drop down menu option idea. Having control over what the LEDs show would be great. Might not be too bad to do.

Ah nice, that's a good price to snap them up, especially new! Cheers for the offer, I'm ok for the mean time 👍

**Comment by elvisimprsntr** [comment]
I updated my dedicated NTP server from 2.7.0-DEVEL to 23.01, then 23.05.   

The lcdproc_{client,screens}.php works great!  Didn't even need to re-install the php files.  

https://github.com/elvisimprsntr/pfsense-lcdproc

🍻

**Comment by georou** [comment]
Nice mate, good to hear! It's looking great
